### PR TITLE
add arch dependencies and versions

### PR DESCRIPTION
**Pull request by dylanhu7**
This is what I needed to do to get it working on Arch.

### CODE REVIEW

**Comment by Antares0982** [comment]
Honestly I modified a few lines to make SIBR compile using ffmpeg version n6.0. But is GCC-12 really needed? I think the latest version on Arch Linux (13.2.1) should also work.

**Comment by dylanhu7** [comment]
I get the following error using 13.2.1 (with or without ninja):
```
SIBR_viewers/src/core/video/VideoUtils.hpp:940:43: error: cannot decompose non-array non-class type ‘const unsigned int’
  940 |                         for (const auto & [key, val] : bins) {
      |                                           ^~~~~~~~~~
```

**Comment by Antares0982** [comment]
Oh I see, in line 967 specialized `class Histogram<T, 1>` defines
```c++
std::vector<uint> bins;
```
which is different from `template<> class Histogram`. So I think this is a bug and should be modified to
```c++
uint getModeIndice() const {
	uint mode, mode_size = 0;
	for (size_t key = 0; key < bins.size(); key++) {
              auto &val = bins[key];
              if (val > mode_size) {
                  mode_size = val;
                  mode = key;
              }
	}
	return mode;
}
```
or just safely delete this method to make it compile (it is never used). I will add some comment on this.
